version: '3.7'

services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=capstone
      - POSTGRES_USER=udacity
      - POSTGRES_PASSWORD=BestPass2021!
  app:
    build:
      context: .
    command: dockerize -wait tcp://postgres:5432 flask run
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=DOCKER
    volumes:
      - .:/home/udacity/
    depends_on:
      - postgres
